DROP DATABASE IF EXISTS blogsite;
CREATE DATABASE IF NOT EXISTS blogsite DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE blogsite;

CREATE TABLE blogs(
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    deleted_at DATETIME NULL DEFAULT NULL,
    id INT(6) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(80) NOT NULL,
    content TEXT NOT NULL,
    author VARCHAR(120) NOT NULL,
    slug VARCHAR(80) NOT NULL
)ENGINE='InnoDB';

CREATE TABLE comments(
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    deleted_at DATETIME NULL DEFAULT NULL,
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    content TEXT NOT NULL,
    author VARCHAR(120) NOT NULL,
    blog_id INT(6) NOT NULL,
    FOREIGN KEY(blog_id) REFERENCES blogs(id) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE='InnoDB';